// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeXFdYnLL7Dku7h8UP_XQJQsL-VPk1m1M',
    appId: '1:845547046753:web:5634cee568d139bc286720',
    messagingSenderId: '845547046753',
    projectId: 'rider-diplomski',
    authDomain: 'rider-diplomski.firebaseapp.com',
    databaseURL: 'https://rider-diplomski-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rider-diplomski.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy6QjH17zuFNrO-j4MvYdh589fO_GSiDk',
    appId: '1:845547046753:android:e146b47d4b04ce09286720',
    messagingSenderId: '845547046753',
    projectId: 'rider-diplomski',
    databaseURL: 'https://rider-diplomski-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rider-diplomski.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEM91WI9MAPwBoGdsV8vi5spp6TD-qLWI',
    appId: '1:845547046753:ios:e12ff86bf7a8be0f286720',
    messagingSenderId: '845547046753',
    projectId: 'rider-diplomski',
    databaseURL: 'https://rider-diplomski-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rider-diplomski.appspot.com',
    iosClientId: '845547046753-cgj8oep7t9h50ismc20e4o1kt8c82lju.apps.googleusercontent.com',
    iosBundleId: 'com.example.diplomskiClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEM91WI9MAPwBoGdsV8vi5spp6TD-qLWI',
    appId: '1:845547046753:ios:e12ff86bf7a8be0f286720',
    messagingSenderId: '845547046753',
    projectId: 'rider-diplomski',
    databaseURL: 'https://rider-diplomski-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rider-diplomski.appspot.com',
    iosClientId: '845547046753-cgj8oep7t9h50ismc20e4o1kt8c82lju.apps.googleusercontent.com',
    iosBundleId: 'com.example.diplomskiClient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqXRdlvJcR5WVqfXlFjMxSYpD5o0eD9LQ',
    appId: '1:845547046753:web:5eeaa1bd8786182b286720',
    messagingSenderId: '845547046753',
    projectId: 'rider-diplomski',
    authDomain: 'rider-diplomski.firebaseapp.com',
    databaseURL: 'https://rider-diplomski-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rider-diplomski.appspot.com',
  );
}
